# db_fake.py
from models import Person, Event, EventParticipant

people = [
    Person(
        id="u0",
        name="Mitsu",
        emoji="🕺",
        country="🇫🇷",
        type="student",
        desc="Always down for a dance & deep talk after.",
        interests=["music", "party", "friends"],
        languages=["Spanish", "English", "French"],
        age=30,
        house="Fondation Deutsch de la Meurthe",
        points=120,
    ),
    Person(
        id="u1",
        name="Lucas",
        emoji="🕺",
        country="🇧🇷",
        type="student",
        desc="Always down for a dance & deep talk after.",
        interests=["music", "party", "friends"],
        languages=["Portuguese", "English", "French"],
        age=23,
        house="Maison du Brésil",
        points=120,
    ),
    Person(
        id="u2",
        name="Ana",
        emoji="🍕",
        country="🇮🇹",
        type="cite",
        desc="Chill foodie who loves spontaneous nights.",
        interests=["food", "travel", "social events"],
        languages=["Italian", "English", "Spanish"],
        age=24,
        house="Maison de l’Italie",
        points=95,
    ),
    Person(
        id="u3",
        name="Max",
        emoji="🎤",
        country="🇩🇪",
        type="student",
        desc="Here for Erasmus — got the playlist 🔥",
        interests=["music", "DJing", "concerts"],
        languages=["German", "English"],
        age=22,
        house="Maison d’Allemagne",
        points=180,
    ),
    Person(
        id="u4",
        name="François",
        emoji="📚",
        country="🇫🇷",
        type="local",
        desc="French lit student who likes to sing.",
        interests=["books", "karaoke", "culture"],
        languages=["French", "English"],
        age=25,
        house="Maison Internationale",
        points=75,
    ),
    Person(
        id="u5",
        name="Emma",
        emoji="🕯️",
        country="🇫🇷",
        type="cite",
        desc="Loves cozy nights with candles and chill chats.",
        interests=["outdoors", "picnics", "board games"],
        languages=["French", "English"],
        age=23,
        house="Fondation Deutsch de la Meurthe",
        points=60,
    ),
    Person(
        id="u6",
        name="Leo",
        emoji="🎸",
        country="🇪🇸",
        type="student",
        desc="Guitar & chill master, always carrying music.",
        interests=["music", "outdoors", "people"],
        languages=["Spanish", "English"],
        age=21,
        house="Maison d’Espagne",
        points=110,
    ),
    Person(
        id="u7",
        name="Sara",
        emoji="🧃",
        country="🇲🇽",
        type="touristic",
        desc="Brings weird snacks and fun stories from Mexico.",
        interests=["food", "friends", "exploring"],
        languages=["Spanish", "English", "French"],
        age=24,
        house="Maison du Mexique",
        points=140,
    ),
    Person(
        id="u8",
        name="Nina",
        emoji="🎲",
        country="🇧🇪",
        type="local",
        desc="Strategy nerd who’s surprisingly competitive.",
        interests=["games", "strategy", "tea"],
        languages=["French", "Dutch", "English"],
        age=27,
        house="Maison de Belgique",
        points=85,
    ),
    Person(
        id="u9",
        name="Mina",
        emoji="🌯",
        country="🇲🇦",
        type="popular",
        desc="Knows every hidden street-food gem in Paris.",
        interests=["food", "travel", "friends"],
        languages=["Arabic", "French", "English"],
        age=26,
        house="Maison du Maroc",
        points=160,
    ),
    Person(
        id="u10",
        name="Huy",
        emoji="🍜",
        country="🇻🇳",
        type="student",
        desc="Pho philosopher who always brings good energy.",
        interests=["food", "philosophy", "music"],
        languages=["Vietnamese", "English", "French"],
        age=23,
        house="Maison de l’Asie du Sud-Est",
        points=130,
    ),
]
events = [
    Event(
        id="e1", 
        name="Karaoke on the Rooftop",
        time="10:00 PM",
        budget=8,
        type= "student", 
        category= "music",
        location= "Belleville Rooftop, Paris 19e",
        description= "Sing under the stars with cheap drinks and great city views.",
        crew= ["u1", "u10"],
        ),
    Event(
        id="e2", 
        name="Night Picnic @ Montsouris",
        time="9:00 PM",
        budget=5,
        type= "touristic", 
        category= "outdoor",
        location= "Parc Montsouris, Paris 14e Rooftop, Paris 19e",
        description= "Candles, cards, and calm vibes around the lake.",
        crew= ["u1", "u2", "u3", "u4", "u5"],
        ),

]


# event_participants = [
#     EventParticipant(id="p1", eventId="e1", userId="u1", status="joined"),
#     EventParticipant(id="p2", eventId="e1", userId="u2", status="joined"),
#     EventParticipant(id="p3", eventId="e2", userId="u3", status="joined"),
#     EventParticipant(id="p4", eventId="e2", userId="u1", status="joined"),
# ]